#!/usr/bin/env node

/**
 * Social Media Analytics Platform Setup Script
 * 
 * This script helps you set up your environment configuration for the analytics platform.
 * Run with: node setup.js
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

async function setup() {
  console.log('\n🚀 Social Media Analytics Platform Setup');
  console.log('========================================\n');
  
  console.log('This script will help you create a .env file with your API credentials.');
  console.log('You can skip any field by pressing Enter (it will use placeholder values).\n');

  const envPath = path.join(__dirname, '.env');
  const examplePath = path.join(__dirname, '.env.example');

  // Check if .env already exists
  if (fs.existsSync(envPath)) {
    const overwrite = await question('⚠️  .env file already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled.');
      rl.close();
      return;
    }
  }

  console.log('\n📊 Database Configuration');
  console.log('------------------------');
  const mongoUri = await question('MongoDB URI [mongodb://localhost:27017/social_media_analytics]: ') || 'mongodb://localhost:27017/social_media_analytics';

  console.log('\n🔐 Security Configuration');
  console.log('------------------------');
  const jwtSecret = await question('JWT Secret (leave empty for random): ') || generateRandomSecret();
  const sessionSecret = await question('Session Secret (leave empty for random): ') || generateRandomSecret();

  console.log('\n📧 Email Configuration (Gmail)');
  console.log('-----------------------------');
  console.log('For Gmail, you need to enable 2FA and create an App Password');
  const emailUser = await question('Gmail address: ');
  const emailPass = await question('Gmail App Password: ');

  console.log('\n📘 Facebook/Instagram API');
  console.log('-------------------------');
  console.log('Get these from https://developers.facebook.com/apps/');
  const facebookAppId = await question('Facebook App ID: ');
  const facebookAppSecret = await question('Facebook App Secret: ');

  console.log('\n🐦 Twitter/X API');
  console.log('---------------');
  console.log('Get these from https://developer.twitter.com/');
  const xApiKey = await question('Twitter API Key: ');
  const xApiSecret = await question('Twitter API Secret: ');
  const xBearerToken = await question('Twitter Bearer Token: ');
  const xClientId = await question('Twitter Client ID (OAuth 2.0): ');
  const xClientSecret = await question('Twitter Client Secret (OAuth 2.0): ');

  console.log('\n💼 LinkedIn API');
  console.log('---------------');
  console.log('Get these from https://www.linkedin.com/developers/apps/');
  const linkedinClientId = await question('LinkedIn Client ID: ');
  const linkedinClientSecret = await question('LinkedIn Client Secret: ');

  console.log('\n☁️  Cloudinary (Optional)');
  console.log('-----------------------');
  console.log('For media uploads, get these from https://cloudinary.com/');
  const cloudinaryName = await question('Cloudinary Cloud Name: ');
  const cloudinaryKey = await question('Cloudinary API Key: ');
  const cloudinarySecret = await question('Cloudinary API Secret: ');

  console.log('\n🤖 AI Configuration (Optional)');
  console.log('-----------------------------');
  const deapiKey = await question('DeAPI Key: ');
  const geminiKey = await question('Gemini AI API Key: ');

  console.log('\n⚙️  Server Configuration');
  console.log('-----------------------');
  const port = await question('Server Port [5000]: ') || '5000';
  const frontendUrl = await question('Frontend URL [http://localhost:3000]: ') || 'http://localhost:3000';

  // Generate .env content
  const envContent = `# Social Media Analytics Platform Environment Configuration
# Generated by setup script on ${new Date().toISOString()}

# Database Configuration
MONGODB_URI=${mongoUri}
DB_NAME=social_media_analytics

# Server Configuration
PORT=${port}
NODE_ENV=development
CORS_ORIGIN=${frontendUrl}

# JWT Configuration
JWT_SECRET=${jwtSecret}
JWT_EXPIRES_IN=24h

# Email Configuration
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_USER=${emailUser}
EMAIL_PASS=${emailPass}
EMAIL_FROM=${emailUser}

# Cloudinary Configuration
CLOUDINARY_CLOUD_NAME=${cloudinaryName}
CLOUDINARY_API_KEY=${cloudinaryKey}
CLOUDINARY_API_SECRET=${cloudinarySecret}

# Facebook/Instagram Graph API Configuration
FACEBOOK_APP_ID=${facebookAppId}
FACEBOOK_APP_SECRET=${facebookAppSecret}
FACEBOOK_REDIRECT_URI=http://localhost:${port}/api/social/auth/facebook/callback

# Instagram Basic Display API
INSTAGRAM_CLIENT_ID=${facebookAppId}
INSTAGRAM_CLIENT_SECRET=${facebookAppSecret}
INSTAGRAM_REDIRECT_URI=http://localhost:${port}/api/social/auth/instagram/callback

# Twitter API Configuration
X_API_KEY=${xApiKey}
X_API_SECRET=${xApiSecret}
X_BEARER_TOKEN=${xBearerToken}
X_CLIENT_ID=${xClientId}
X_CLIENT_SECRET=${xClientSecret}
X_REDIRECT_URI=http://localhost:${port}/api/social/auth/x/callback

# LinkedIn API Configuration
LINKEDIN_CLIENT_ID=${linkedinClientId}
LINKEDIN_CLIENT_SECRET=${linkedinClientSecret}
LINKEDIN_REDIRECT_URI=http://localhost:${port}/api/social/auth/linkedin/callback

# AI Configuration
DEAPI_KEY=${deapiKey}
GEMINI_API_KEY=${geminiKey}

# Security Configuration
BCRYPT_SALT_ROUNDS=12
SESSION_SECRET=${sessionSecret}

# Frontend URL
FRONTEND_URL=${frontendUrl}

# Rate Limiting Configuration
RATE_LIMIT_WINDOW=15
RATE_LIMIT_MAX_REQUESTS=100

# File Upload Configuration
MAX_FILE_SIZE=5242880
UPLOAD_DIR=./uploads

# Analytics Configuration
ANALYTICS_CACHE_TTL=300
MAX_ANALYTICS_HISTORY=90
`;

  // Write .env file
  fs.writeFileSync(envPath, envContent);

  console.log('\n✅ Setup Complete!');
  console.log('==================');
  console.log(`📁 Created .env file at: ${envPath}`);
  console.log('\n📋 Next Steps:');
  console.log('1. Review your .env file and add any missing values');
  console.log('2. Set up your MongoDB database (local or Atlas)');
  console.log('3. Configure OAuth redirect URIs in your app dashboards:');
  console.log(`   - Facebook: http://localhost:${port}/api/social/auth/facebook/callback`);
  console.log(`   - Twitter: http://localhost:${port}/api/social/auth/x/callback`);
  console.log(`   - LinkedIn: http://localhost:${port}/api/social/auth/linkedin/callback`);
  console.log('4. Start your application with: npm run dev');
  
  console.log('\n🔧 Configuration URLs:');
  console.log('- Facebook Developers: https://developers.facebook.com/apps/');
  console.log('- Twitter Developer Portal: https://developer.twitter.com/');
  console.log('- LinkedIn Developers: https://www.linkedin.com/developers/apps/');
  console.log('- Cloudinary Console: https://cloudinary.com/console');

  rl.close();
}

function generateRandomSecret() {
  return require('crypto').randomBytes(32).toString('hex');
}

// Handle Ctrl+C gracefully
process.on('SIGINT', () => {
  console.log('\n\nSetup cancelled by user.');
  rl.close();
  process.exit(0);
});

// Run setup
setup().catch(error => {
  console.error('Setup failed:', error);
  rl.close();
  process.exit(1);
});